version: '3.8'

services:
  node-app:
    build: .
    container_name: node-app
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    command: npm start
